name: Beta Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Java setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
          check-latest: true
      - name: Set version
        run: |
          echo "VERSION=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF#refs/*/}" >> "$GITHUB_ENV"
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Config repo
        run: python config_version.py
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: jdk8
          arguments: build --no-build-cache
          gradle-version: wrapper
      - name: Upload Artifact
        run: |
          cd build/libs
          zip minusbounce.zip *
          curl --connect-timeout 30 -m 300 -X POST -H "Authorization: Bearer ${{ secrets.SERVER_TOKEN }}" -F "commit=${{ env.VERSION }}" -F "branch=${{ env.BRANCH }}" -F "message=${{ github.event.head_commit.message }}" -F "artifact=@minusbounce.zip;type=application/zip" https://api.minusbounce.lol/beta
#      - name: Publish package
#        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#        with:
#          arguments: publish
#        env:
#          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
#          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
#        if: ${{startsWith(github.repository, 'MinusMCNetwork')}}

